name = "     yash       "
dots = ".............."
print(name+dots) # it gives -->      yash     ..........
# So to remove these spaces we use strip method
# 1.) lstrip()
print(name.lstrip()+dots) # it gives -->yash     ..........

# 2.) rstrip()
print(name.rstrip()+dots) # it gives -->        yash........

#3.) strip()
print(name.strip()+dots) # it gives -->yash........

name1 = "     ya   sh"
print(name1.strip()+dots) # it gives --> ya   sh........
# it doesn't remove spaces between letters , so we have to replace it
print(name1.replace(" ","")+dots) # it gives --> yash........